import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import {Providers, RecoilProvider} from "./provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mind Canvas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
        <RecoilProvider>

          <Providers>
          {children}
          </Providers>
        </RecoilProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
